import BasicPhone from "../src/images/BasicPhone.jpeg";
import BrickPhone from "../src/images/BrickPhone.jpeg";
import Phone2 from "../src/images/Phone2.jpeg";
import Oldphone from "../src/images/OldPhone.jpeg";

export const productdata = [
        {
          "id": 101,
          "name": "SmartPhone X Pro",
          "cost": 799.99,
          "stock": 25,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 102,
          "name": "SmartPhone X Plus",
          "cost": 699.99,
          "stock": 30,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 103,
          "name": "SmartPhone Y Ultra",
          "cost": 899.99,
          "stock": 15,
          "picture": Phone2,
          "about": "Introducing the **SmartPhone Y™**—the sidegrade that brings you all the essential features of a premium device, with a fresh, modern twist. If you're looking for a phone that delivers reliable performance without the premium price tag, the **SmartPhone Y™** offers everything you need to stay connected and productive, all in a sleek and budget-friendly package. The **SmartPhone Y™** features a sharp, clear display that’s perfect for watching videos, browsing the web, and staying connected on social media. Its responsive touchscreen makes navigation a breeze, while the efficient processor ensures that your apps run smoothly—whether you're sending messages, checking emails, or enjoying your favorite apps. With a compact, lightweight design, the **SmartPhone Y™** fits comfortably in your hand and is easy to carry, making it the perfect companion for everyday use. The battery life is optimized for longer usage, so you can stay powered up throughout your busy day without worrying about constant recharging. Capture the moments that matter with a reliable camera system, whether it's a quick selfie or a snapshot of your surroundings. Plus, with access to a wide range of apps, you can customize your experience and make the most out of your device. **Key Features:**  **Clear Display**: Enjoy bright, sharp visuals for everyday tasks and media consumption. **Efficient Performance**: A responsive processor that handles apps and multitasking with ease. **Compact and Lightweight**: Perfectly designed for one-handed use and portability. **Extended Battery Life**: Use your phone throughout the day without the need for frequent charging. **Reliable Camera**: Take quality photos and videos for all your important moments. **App Access**: Enjoy a wide selection of apps to enhance your daily experience. The **SmartPhone Y™** is the perfect sidegrade for anyone looking for a smart, practical device without the frills of higher-end models. It’s a no-compromise phone that gives you all the essentials, with a focus on affordability and usability. Whether you’re texting, browsing, or capturing memories, the **SmartPhone Y™** does it all with style and ease."
        },
        {
          "id": 104,
          "name": "BrickPhone",
          "cost": 999.99,
          "stock": 10,
          "picture": BrickPhone,
          "about": "Introducing the **BrickPhone™**—the phone that redefines ruggedness and durability, blending old-school charm with modern functionality. Crafted from solid bricks, this phone is the ultimate statement in robustness. It’s built to withstand extreme drops, harsh weather conditions, and even the most intense construction zones. The **BrickPhone™** features a thick, brick-like exterior that gives it an iconic, bulky look, reminiscent of a bygone era of mobile phones—but don’t let the hefty build fool you. Inside, it packs all the essential tech features you'd expect from a high-end device: a large, pixelated display, physical buttons that provide satisfying tactile feedback, and a surprisingly responsive touchscreen interface.With a battery life that could last for days (thanks to its minimalist energy requirements), the **BrickPhone™** will keep you connected longer than your typical smartphone. And if you ever need to make an emergency call or, dare we say, defend yourself, the weight and hardness of the phone can certainly pack a punch. For the true adventurer, builder, or anyone looking for a phone that will survive any condition—whether it’s rain, snow, or being crushed under a pile of debris—the **BrickPhone™** is the phone that won't back down. **Key Features:**- **Unbeatable Durability**: Made from reinforced bricks, ensuring protection against extreme drops and impacts. **Long-lasting Battery**: Minimalist design maximizes battery life for extended use. **Retro Tech**: Classic, physical buttons with a modern twist of a digital display and touch capability. **Enhanced Security**: Heavy-duty build means it can handle almost any physical stress. **Unique Design**: Stand out with a phone that looks like it could double as a paperweight or a building block. Get ready for the most indestructible, unconventional, and surprisingly functional phone—perfect for those who prioritize toughness over sleekness. The **BrickPhone™**: for those who aren't afraid to go back to basics... and maybe drop a few bricks along the way."
        },
        {
          "id": 105,
          "name": "SmartPhone X Mini",
          "cost": 499.99,
          "stock": 40,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 106,
          "name": "SmartPhone Y Lite",
          "cost": 349.99,
          "stock": 50,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 107,
          "name": "SmartPhone Z Ultra",
          "cost": 1099.99,
          "stock": 8,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 108,
          "name": "SmartPhone X Pro Max",
          "cost": 1299.99,
          "stock": 5,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 109,
          "name": "Bell Phone 78",
          "cost": 799.99,
          "stock": 20,
          "picture": Oldphone,
          "about": "Introducing the **Bell Phone 78™**—a classic piece of technology from 1878, designed to give you a no-nonsense mobile experience. If you're looking for simplicity and reliability, the **Bell Phone 78™** is a throwback to a time when phones were just about calling, and nothing more. With its sturdy, ergonomic design and tactile buttons, the **Bell Phone 78™** delivers a satisfying, retro feel. The black-and-white display provides just the essentials: the time, signal strength, and your incoming calls. Forget apps, screens full of notifications, or endless customization—this phone is all about making calls and staying connected, no distractions necessary. Built like a tank, the **Bell Phone 78™** is constructed to last. The durable, solid plastic body can withstand the rigors of daily use, and its long-lasting battery can keep you chatting for hours without worrying about charging every day. You’ll never have to stress about over-complicated settings—just plug in your phone, and it’s ready to go. The **Bell Phone 78™** keeps it simple with a basic keypad for dialing numbers, so you can make calls quickly and efficiently. No touchscreen to fiddle with, no complicated menus, just clear and easy access to the people that matter most. **Key Features:** **Sturdy, Retro Design**: Classic, reliable construction built to last. **Simple Interface**: No-touchscreen, just straightforward buttons for dialing. **Long Battery Life**: Talk for hours on end without needing to recharge. **Durability**: The tough, durable body can handle drops and bumps with ease. **Basic Call Functionality**: Focused on what really matters—staying connected. The **Bell Phone 78™** is for those who want a no-frills, dependable phone that takes them back to the essentials of communication. It’s not about apps, cameras, or fancy features—it’s about a device that gets you in touch with others, without the distractions of today’s modern smartphones. Perfect for those who appreciate simplicity, durability, and nostalgia."
        },
        {
          "id": 110,
          "name": "SmartPhone Z Lite",
          "cost": 399.99,
          "stock": 35,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 111,
          "name": "SmartPhon2 X Pro",
          "cost": 799.99,
          "stock": 25,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 112,
          "name": "SmartPhon2 X Plus",
          "cost": 699.99,
          "stock": 30,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 113,
          "name": "SmartPhon2 Y Ultra",
          "cost": 899.99,
          "stock": 15,
          "picture": Phone2,
          "about": "Introducing the **SmartPhone Y™**—the sidegrade that brings you all the essential features of a premium device, with a fresh, modern twist. If you're looking for a phone that delivers reliable performance without the premium price tag, the **SmartPhone Y™** offers everything you need to stay connected and productive, all in a sleek and budget-friendly package. The **SmartPhone Y™** features a sharp, clear display that’s perfect for watching videos, browsing the web, and staying connected on social media. Its responsive touchscreen makes navigation a breeze, while the efficient processor ensures that your apps run smoothly—whether you're sending messages, checking emails, or enjoying your favorite apps. With a compact, lightweight design, the **SmartPhone Y™** fits comfortably in your hand and is easy to carry, making it the perfect companion for everyday use. The battery life is optimized for longer usage, so you can stay powered up throughout your busy day without worrying about constant recharging. Capture the moments that matter with a reliable camera system, whether it's a quick selfie or a snapshot of your surroundings. Plus, with access to a wide range of apps, you can customize your experience and make the most out of your device. **Key Features:**  **Clear Display**: Enjoy bright, sharp visuals for everyday tasks and media consumption. **Efficient Performance**: A responsive processor that handles apps and multitasking with ease. **Compact and Lightweight**: Perfectly designed for one-handed use and portability. **Extended Battery Life**: Use your phone throughout the day without the need for frequent charging. **Reliable Camera**: Take quality photos and videos for all your important moments. **App Access**: Enjoy a wide selection of apps to enhance your daily experience. The **SmartPhone Y™** is the perfect sidegrade for anyone looking for a smart, practical device without the frills of higher-end models. It’s a no-compromise phone that gives you all the essentials, with a focus on affordability and usability. Whether you’re texting, browsing, or capturing memories, the **SmartPhone Y™** does it all with style and ease."
        },
        {
          "id": 114,
          "name": "BrickPhon2",
          "cost": 999.99,
          "stock": 10,
          "picture": BrickPhone,
          "about": "Introducing the **BrickPhone™**—the phone that redefines ruggedness and durability, blending old-school charm with modern functionality. Crafted from solid bricks, this phone is the ultimate statement in robustness. It’s built to withstand extreme drops, harsh weather conditions, and even the most intense construction zones. The **BrickPhone™** features a thick, brick-like exterior that gives it an iconic, bulky look, reminiscent of a bygone era of mobile phones—but don’t let the hefty build fool you. Inside, it packs all the essential tech features you'd expect from a high-end device: a large, pixelated display, physical buttons that provide satisfying tactile feedback, and a surprisingly responsive touchscreen interface.With a battery life that could last for days (thanks to its minimalist energy requirements), the **BrickPhone™** will keep you connected longer than your typical smartphone. And if you ever need to make an emergency call or, dare we say, defend yourself, the weight and hardness of the phone can certainly pack a punch. For the true adventurer, builder, or anyone looking for a phone that will survive any condition—whether it’s rain, snow, or being crushed under a pile of debris—the **BrickPhone™** is the phone that won't back down. **Key Features:**- **Unbeatable Durability**: Made from reinforced bricks, ensuring protection against extreme drops and impacts. **Long-lasting Battery**: Minimalist design maximizes battery life for extended use. **Retro Tech**: Classic, physical buttons with a modern twist of a digital display and touch capability. **Enhanced Security**: Heavy-duty build means it can handle almost any physical stress. **Unique Design**: Stand out with a phone that looks like it could double as a paperweight or a building block. Get ready for the most indestructible, unconventional, and surprisingly functional phone—perfect for those who prioritize toughness over sleekness. The **BrickPhone™**: for those who aren't afraid to go back to basics... and maybe drop a few bricks along the way."
        },
        {
          "id": 115,
          "name": "SmartPhon2 X Mini",
          "cost": 499.99,
          "stock": 40,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 116,
          "name": "SmartPhon2 Y Lite",
          "cost": 349.99,
          "stock": 50,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 117,
          "name": "SmartPhon2 Z Ultra",
          "cost": 1099.99,
          "stock": 8,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 118,
          "name": "SmartPhon2 X Pro Max",
          "cost": 1299.99,
          "stock": 5,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 119,
          "name": "Bell Phon2 78",
          "cost": 799.99,
          "stock": 20,
          "picture": Oldphone,
          "about": "Introducing the **Bell Phone 78™**—a classic piece of technology from 1878, designed to give you a no-nonsense mobile experience. If you're looking for simplicity and reliability, the **Bell Phone 78™** is a throwback to a time when phones were just about calling, and nothing more. With its sturdy, ergonomic design and tactile buttons, the **Bell Phone 78™** delivers a satisfying, retro feel. The black-and-white display provides just the essentials: the time, signal strength, and your incoming calls. Forget apps, screens full of notifications, or endless customization—this phone is all about making calls and staying connected, no distractions necessary. Built like a tank, the **Bell Phone 78™** is constructed to last. The durable, solid plastic body can withstand the rigors of daily use, and its long-lasting battery can keep you chatting for hours without worrying about charging every day. You’ll never have to stress about over-complicated settings—just plug in your phone, and it’s ready to go. The **Bell Phone 78™** keeps it simple with a basic keypad for dialing numbers, so you can make calls quickly and efficiently. No touchscreen to fiddle with, no complicated menus, just clear and easy access to the people that matter most. **Key Features:** **Sturdy, Retro Design**: Classic, reliable construction built to last. **Simple Interface**: No-touchscreen, just straightforward buttons for dialing. **Long Battery Life**: Talk for hours on end without needing to recharge. **Durability**: The tough, durable body can handle drops and bumps with ease. **Basic Call Functionality**: Focused on what really matters—staying connected. The **Bell Phone 78™** is for those who want a no-frills, dependable phone that takes them back to the essentials of communication. It’s not about apps, cameras, or fancy features—it’s about a device that gets you in touch with others, without the distractions of today’s modern smartphones. Perfect for those who appreciate simplicity, durability, and nostalgia."
        },
        {
          "id": 120,
          "name": "SmartPhon3 Z Lite",
          "cost": 399.99,
          "stock": 35,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 121,
          "name": "SmartPhon3 X Pro",
          "cost": 799.99,
          "stock": 25,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 122,
          "name": "SmartPhon3 X Plus",
          "cost": 699.99,
          "stock": 30,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 123,
          "name": "SmartPhon3 Y Ultra",
          "cost": 899.99,
          "stock": 15,
          "picture": Phone2,
          "about": "Introducing the **SmartPhone Y™**—the sidegrade that brings you all the essential features of a premium device, with a fresh, modern twist. If you're looking for a phone that delivers reliable performance without the premium price tag, the **SmartPhone Y™** offers everything you need to stay connected and productive, all in a sleek and budget-friendly package. The **SmartPhone Y™** features a sharp, clear display that’s perfect for watching videos, browsing the web, and staying connected on social media. Its responsive touchscreen makes navigation a breeze, while the efficient processor ensures that your apps run smoothly—whether you're sending messages, checking emails, or enjoying your favorite apps. With a compact, lightweight design, the **SmartPhone Y™** fits comfortably in your hand and is easy to carry, making it the perfect companion for everyday use. The battery life is optimized for longer usage, so you can stay powered up throughout your busy day without worrying about constant recharging. Capture the moments that matter with a reliable camera system, whether it's a quick selfie or a snapshot of your surroundings. Plus, with access to a wide range of apps, you can customize your experience and make the most out of your device. **Key Features:**  **Clear Display**: Enjoy bright, sharp visuals for everyday tasks and media consumption. **Efficient Performance**: A responsive processor that handles apps and multitasking with ease. **Compact and Lightweight**: Perfectly designed for one-handed use and portability. **Extended Battery Life**: Use your phone throughout the day without the need for frequent charging. **Reliable Camera**: Take quality photos and videos for all your important moments. **App Access**: Enjoy a wide selection of apps to enhance your daily experience. The **SmartPhone Y™** is the perfect sidegrade for anyone looking for a smart, practical device without the frills of higher-end models. It’s a no-compromise phone that gives you all the essentials, with a focus on affordability and usability. Whether you’re texting, browsing, or capturing memories, the **SmartPhone Y™** does it all with style and ease."
        },
        {
          "id": 124,
          "name": "BrickPhon3",
          "cost": 999.99,
          "stock": 10,
          "picture": BrickPhone,
          "about": "Introducing the **BrickPhone™**—the phone that redefines ruggedness and durability, blending old-school charm with modern functionality. Crafted from solid bricks, this phone is the ultimate statement in robustness. It’s built to withstand extreme drops, harsh weather conditions, and even the most intense construction zones. The **BrickPhone™** features a thick, brick-like exterior that gives it an iconic, bulky look, reminiscent of a bygone era of mobile phones—but don’t let the hefty build fool you. Inside, it packs all the essential tech features you'd expect from a high-end device: a large, pixelated display, physical buttons that provide satisfying tactile feedback, and a surprisingly responsive touchscreen interface.With a battery life that could last for days (thanks to its minimalist energy requirements), the **BrickPhone™** will keep you connected longer than your typical smartphone. And if you ever need to make an emergency call or, dare we say, defend yourself, the weight and hardness of the phone can certainly pack a punch. For the true adventurer, builder, or anyone looking for a phone that will survive any condition—whether it’s rain, snow, or being crushed under a pile of debris—the **BrickPhone™** is the phone that won't back down. **Key Features:**- **Unbeatable Durability**: Made from reinforced bricks, ensuring protection against extreme drops and impacts. **Long-lasting Battery**: Minimalist design maximizes battery life for extended use. **Retro Tech**: Classic, physical buttons with a modern twist of a digital display and touch capability. **Enhanced Security**: Heavy-duty build means it can handle almost any physical stress. **Unique Design**: Stand out with a phone that looks like it could double as a paperweight or a building block. Get ready for the most indestructible, unconventional, and surprisingly functional phone—perfect for those who prioritize toughness over sleekness. The **BrickPhone™**: for those who aren't afraid to go back to basics... and maybe drop a few bricks along the way."
        },
        {
          "id": 125,
          "name": "SmartPhon3 X Mini",
          "cost": 499.99,
          "stock": 40,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 126,
          "name": "SmartPhon3 Y Lite",
          "cost": 349.99,
          "stock": 50,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 127,
          "name": "SmartPhon3 Z Ultra",
          "cost": 1099.99,
          "stock": 8,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 128,
          "name": "SmartPhon3 X Pro Max",
          "cost": 1299.99,
          "stock": 5,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        },
        {
          "id": 129,
          "name": "Bell Phone 79",
          "cost": 799.99,
          "stock": 20,
          "picture": Oldphone,
          "about": "Introducing the **Bell Phone 78™**—a classic piece of technology from 1878, designed to give you a no-nonsense mobile experience. If you're looking for simplicity and reliability, the **Bell Phone 78™** is a throwback to a time when phones were just about calling, and nothing more. With its sturdy, ergonomic design and tactile buttons, the **Bell Phone 78™** delivers a satisfying, retro feel. The black-and-white display provides just the essentials: the time, signal strength, and your incoming calls. Forget apps, screens full of notifications, or endless customization—this phone is all about making calls and staying connected, no distractions necessary. Built like a tank, the **Bell Phone 78™** is constructed to last. The durable, solid plastic body can withstand the rigors of daily use, and its long-lasting battery can keep you chatting for hours without worrying about charging every day. You’ll never have to stress about over-complicated settings—just plug in your phone, and it’s ready to go. The **Bell Phone 78™** keeps it simple with a basic keypad for dialing numbers, so you can make calls quickly and efficiently. No touchscreen to fiddle with, no complicated menus, just clear and easy access to the people that matter most. **Key Features:** **Sturdy, Retro Design**: Classic, reliable construction built to last. **Simple Interface**: No-touchscreen, just straightforward buttons for dialing. **Long Battery Life**: Talk for hours on end without needing to recharge. **Durability**: The tough, durable body can handle drops and bumps with ease. **Basic Call Functionality**: Focused on what really matters—staying connected. The **Bell Phone 78™** is for those who want a no-frills, dependable phone that takes them back to the essentials of communication. It’s not about apps, cameras, or fancy features—it’s about a device that gets you in touch with others, without the distractions of today’s modern smartphones. Perfect for those who appreciate simplicity, durability, and nostalgia."
        },
        {
          "id": 130,
          "name": "SmartPhon3 Z Lite",
          "cost": 399.99,
          "stock": 35,
          "picture": BasicPhone,
          "about": "Introducing the **SmartPhone™**—the quintessential device for the modern world. Whether you're staying connected with loved ones, working on the go, or exploring new ways to entertain yourself, the **SmartPhone™** offers everything you need in one sleek, powerful package. The **SmartPhone™** features a stunning high-definition display that brings your content to life with vibrant colors and sharp details. With its ultra-responsive touchscreen and powerful processor, navigating apps, browsing the web, and playing games has never been smoother or faster. Designed with convenience in mind, the **SmartPhone™** boasts a lightweight, slim body that fits comfortably in your hand and easily slips into your pocket or bag. Its long-lasting battery ensures you can keep up with your busy day, whether you're on a video call, capturing photos, or just enjoying some downtime. With a powerful camera system, the **SmartPhone™** lets you capture memories in stunning detail, from everyday moments to once-in-a-lifetime events. Stay connected with fast and reliable internet, enjoy access to thousands of apps, and rely on seamless integration with other devices for a fully connected experience. **Key Features:** **Vibrant Display**: Enjoy crisp, bright visuals for videos, photos, and apps. **Speed and Power**: Fast processor for smooth multitasking and gaming. **Long-lasting Battery**: Stay powered up throughout your busy day. **Sleek and Stylish**: Modern design that fits perfectly in your hand. **Advanced Camera System**: Capture moments with stunning clarity. **Seamless Connectivity**: Stay connected with fast Wi-Fi and network speeds. The **SmartPhone™** is designed to keep up with your lifestyle, offering the perfect balance of performance, convenience, and style. Whether you're working, learning, or simply enjoying the moment, the **SmartPhone™** is the one device you need to do it all."
        }
      
]